name: Test

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn test
